### ISSUE TITLE
Syncing with hugofara/lwt fork

### ISSUE THREAD

**Issue by HugoFara** [chaosarium/lwt#2]
Hi @chaosarium!

I saw you unarchived your repository, so now we can discuss on pull requests :)

For now, the most simple way to proceed is for you to create a new branch from  commit [e4aeaedc91164e18be9744fcf062553287c2b35f](https://github.com/chaosarium/lwt/commit/e4aeaedc91164e18be9744fcf062553287c2b35f), the commit I forked from.

With that branch we could do a nice pull with fast-forwarding (no conflict), and start a discussion for a bigger pull request on the master branch.

Is it OK for you?

**Comment by chaosarium** [comment]
Hi!

Sorry for a delayed reply. I am current in the middle of several other projects but I'll look into this as soon as I have time :)

**Comment by chaosarium** [comment]
Yap. I just created a new branch from the commit you mentioned and had it synced with your dev branch.
